In [9]:
comps[["competition_name", "season_name", "competition_id", "season_id"]]

          competition_name season_name  competition_id  season_id
0            1. Bundesliga   2023/2024               9        281
1            1. Bundesliga   2015/2016               9         27
2   African Cup of Nations        2023            1267        107
3         Champions League   2018/2019              16          4
4         Champions League   2017/2018              16          1
..                     ...         ...             ...        ...
75      UEFA Europa League   1988/1989              35         75
76       UEFA Women's Euro        2025              53        315
77       UEFA Women's Euro        2022              53        106
78       Women's World Cup        2023              72        107
79       Women's World Cup        2019              72         30

[80 rows x 4 columns]

In [10]:
matches = sb.matches(competition_id=43, season_id=106)
matches.shape

/home/matias-peralta/personalP/football-dw/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(64, 55)

In [11]:
events = sb.events(match_id=matches["match_id"].iloc[0])
events["type"].value_counts()

type
Pass                 955
Ball Receipt*        868
Carry                782
Pressure             289
Ball Recovery         93
Duel                  63
Clearance             41
Dribble               39
Miscontrol            32
Foul Committed        31
Foul Won              31
Block                 27
Dispossessed          23
Dribbled Past         23
Interception          23
Goal Keeper           16
Shot                  12
Substitution          10
Tactical Shift         5
Half Start             4
Half End               4
Injury Stoppage        4
Referee Ball-Drop      4
Starting XI            2
50/50                  2
Error                  1
Shield                 1
Own Goal For           1
Own Goal Against       1
Offside                1
Name: count, dtype: int64

In [12]:
comps[comps["competition_name"].str.contains("World Cup")]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
29,1470,274,International,FIFA U20 World Cup,male,True,True,1979,2024-02-13T14:20:59.825440,NaN,NaN,2024-02-13T14:20:59.825440
30,43,106,International,FIFA World Cup,male,False,True,2022,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717,2026-05-04T01:53:40.309717,2026-05-04T01:48:57.914346
31,43,3,International,FIFA World Cup,male,False,True,2018,2026-05-15T15:48:12.789440,2021-06-13T16:17:31.694,NaN,2026-05-15T15:48:12.789440
32,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694,NaN,2023-06-28T10:58:20.137929
33,43,54,International,FIFA World Cup,male,False,True,1986,2026-05-04T01:30:23.212111,2021-06-13T16:17:31.694,NaN,2026-05-04T01:30:23.212111
34,43,51,International,FIFA World Cup,male,False,True,1974,2026-05-15T02:20:43.439689,2021-06-13T16:17:31.694,NaN,2026-05-15T02:20:43.439689
35,43,272,International,FIFA World Cup,male,False,True,1970,2026-05-04T02:09:10.916859,NaN,NaN,2026-05-04T02:09:10.916859
36,43,270,International,FIFA World Cup,male,False,True,1962,2026-05-04T02:05:35.653887,NaN,NaN,2026-05-04T02:05:35.653887
37,43,269,International,FIFA World Cup,male,False,True,1958,2026-05-04T02:02:41.853159,NaN,NaN,2026-05-04T02:02:41.853159
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,NaN,2026-05-15T15:31:40.299642

In [13]:
import duckdb

con = duckdb.connect("data/football.duckdb")

# Total event count
con.execute("SELECT count(*) FROM raw.events").df()

   count_star()
0        234637

In [14]:
con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'raw'").df()

     table_name
0  competitions
1        events
2       matches